#!/usr/bin/env python3
"""Convert an AsciiDoc file to PDF using the asciidoctor/docker-asciidoctor image.

Usage:
    python convert_to_pdf.py <working_dir> <adoc_filename> [layout_file]

- working_dir: directory containing the .adoc file (mounted into the container).
- adoc_filename: name of the .adoc file, relative to working_dir.
- layout_file: optional path to a pdf-theme YAML file, may live outside working_dir.
"""
import argparse
import glob
import os
import shlex
import sys
import uuid

import docker
from docker.errors import ContainerError, ImageNotFound

IMAGE = "asciidoctor/docker-asciidoctor"
CONTAINER_WORKDIR = "/documents"
# Files generated by asciidoctor-diagram / asciidoctor-mathematical next to the source file.
GENERATED_SVG_GLOBS = ["diag-*.svg", "stem-*.svg"]


def build_shell_command(basename: str, adoc_filename: str, theme_filename: str | None) -> str:
    parts = [
        "asciidoctor-pdf",
        "-r", "asciidoctor-mathematical",
        "-r", "asciidoctor-diagram",
        "-a", "allow-uri-read",
        "-a", "stem",
        "-a", "mathematical-format=svg",
    ]
    if theme_filename:
        parts += ["-a", f"pdf-theme={theme_filename}", "-a", f"pdf-themesdir={CONTAINER_WORKDIR}"]
    parts += ["-o", f"{basename}.pdf", adoc_filename]
    command = " ".join(shlex.quote(p) for p in parts)
    return f"{command} && rm -rf .asciidoctor"


def cleanup_generated_svgs(working_dir: str) -> None:
    for pattern in GENERATED_SVG_GLOBS:
        for path in glob.glob(os.path.join(working_dir, pattern)):
            os.remove(path)


def convert(working_dir: str, adoc_filename: str, layout_file: str | None) -> str:
    working_dir = os.path.abspath(working_dir)
    adoc_path = os.path.join(working_dir, adoc_filename)
    if not os.path.isfile(adoc_path):
        raise FileNotFoundError(f"AsciiDoc file not found: {adoc_path}")

    basename, _ = os.path.splitext(adoc_filename)
    theme_filename = None
    theme_copy_path = None

    if layout_file:
        layout_file = os.path.abspath(layout_file)
        if not os.path.isfile(layout_file):
            raise FileNotFoundError(f"Layout file not found: {layout_file}")
        theme_ext = os.path.splitext(layout_file)[1]
        theme_filename = f".asciidoc-theme-{uuid.uuid4().hex}{theme_ext}"
        theme_copy_path = os.path.join(working_dir, theme_filename)
        with open(layout_file, "rb") as src, open(theme_copy_path, "wb") as dst:
            dst.write(src.read())

    shell_command = build_shell_command(basename, adoc_filename, theme_filename)
    client = docker.from_env()

    try:
        output = client.containers.run(
            image=IMAGE,
            command=["sh", "-c", shell_command],
            volumes={working_dir: {"bind": CONTAINER_WORKDIR, "mode": "rw"}},
            working_dir=CONTAINER_WORKDIR,
            remove=True,
            stdout=True,
            stderr=True,
        )
        sys.stdout.write(output.decode("utf-8", errors="replace"))
    except ImageNotFound:
        raise RuntimeError(
            f"Docker image '{IMAGE}' was not found and could not be pulled. "
            "Check your internet connection or pull it manually."
        )
    except ContainerError as exc:
        stderr = exc.stderr.decode("utf-8", errors="replace") if exc.stderr else ""
        raise RuntimeError(f"asciidoctor-pdf failed (exit code {exc.exit_status}):\n{stderr}")
    finally:
        if theme_copy_path and os.path.isfile(theme_copy_path):
            os.remove(theme_copy_path)
        cleanup_generated_svgs(working_dir)

    pdf_path = os.path.join(working_dir, f"{basename}.pdf")
    if not os.path.isfile(pdf_path):
        raise RuntimeError(f"Conversion reported success but PDF is missing: {pdf_path}")
    return pdf_path


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("working_dir", help="Directory containing the .adoc file")
    parser.add_argument("adoc_filename", help="Name of the .adoc file, relative to working_dir")
    parser.add_argument("layout_file", nargs="?", default=None, help="Optional pdf-theme YAML file")
    args = parser.parse_args()

    try:
        pdf_path = convert(args.working_dir, args.adoc_filename, args.layout_file)
    except (FileNotFoundError, RuntimeError) as exc:
        print(f"Error: {exc}", file=sys.stderr)
        sys.exit(1)

    print(f"PDF created: {pdf_path}")


if __name__ == "__main__":
    main()
