"""PostgreSQL dialect."""

from __future__ import annotations

from .column import Column
from .dialect import Dialect
from .table import Table


class PostgresDialect(Dialect):
    """PostgreSQL: native BOOLEAN, identity columns that accept explicit values."""

    name = "postgres"

    _TYPES = {"int": "INTEGER", "bigint": "BIGINT", "float": "DOUBLE PRECISION", "text": "TEXT",
              "bool": "BOOLEAN", "date": "DATE", "datetime": "TIMESTAMP(0)"}

    def column_type(self, column: Column) -> str:
        if column.type == "string":
            return f"VARCHAR({column.length})"
        if column.type == "decimal":
            return f"DECIMAL({column.precision},{column.scale})"
        return self._TYPES[column.type]

    def identity_clause(self) -> str:
        return "GENERATED BY DEFAULT AS IDENTITY"

    def bool_literal(self, value: bool) -> str:
        return "TRUE" if value else "FALSE"

    def after_data(self, tables: tuple[Table, ...]) -> list[str]:
        # Explicit key values do not advance the identity sequence; without this the next
        # INSERT of a student would fail with a duplicate key.
        statements = []
        for table in tables:
            column = table.identity_column
            if column:
                statements.append(f"SELECT setval(pg_get_serial_sequence('{table.name.lower()}', "
                                  f"'{column.name.lower()}'), (SELECT MAX({column.name}) FROM {table.name}));")
        return statements
