"""Keywords that must not be used as identifiers.

Identifiers are written unquoted in every dialect so students can type them freely.
That only works if no table or column collides with a reserved keyword of SQL Server,
PostgreSQL or SQLite.
"""

RESERVED_WORDS: frozenset[str] = frozenset(
    """
    ADD ALL ALTER ANALYSE ANALYZE AND ANY ARRAY AS ASC ASYMMETRIC AUTHORIZATION BACKUP BEGIN
    BETWEEN BINARY BOTH BREAK BROWSE BULK BY CASCADE CASE CAST CHECK CHECKPOINT CLOSE
    CLUSTERED COALESCE COLLATE COLLATION COLUMN COMMIT COMPUTE CONCURRENTLY CONSTRAINT
    CONTAINS CONTAINSTABLE CONTINUE CONVERT CREATE CROSS CURRENT CURRENT_CATALOG CURRENT_DATE
    CURRENT_ROLE CURRENT_TIME CURRENT_TIMESTAMP CURRENT_USER CURSOR DATABASE DBCC DEALLOCATE
    DECLARE DEFAULT DEFERRABLE DELETE DENY DESC DISK DISTINCT DISTRIBUTED DO DOUBLE DROP DUMP
    ELSE END ERRLVL ESCAPE EXCEPT EXEC EXECUTE EXISTS EXIT EXTERNAL FALSE FETCH FILE
    FILLFACTOR FOR FOREIGN FREETEXT FREETEXTTABLE FREEZE FROM FULL FUNCTION GLOB GOTO GRANT
    GROUP HAVING HOLDLOCK IDENTITY IDENTITY_INSERT IDENTITYCOL IF ILIKE IN INDEX INITIALLY
    INNER INSERT INTERSECT INTO IS ISNULL JOIN KEY KILL LATERAL LEADING LEFT LIKE LIMIT LINENO
    LOAD LOCALTIME LOCALTIMESTAMP MERGE NATIONAL NATURAL NOCHECK NONCLUSTERED NOT NOTNULL NULL
    NULLIF OF OFF OFFSET OFFSETS ON ONLY OPEN OPENDATASOURCE OPENQUERY OPENROWSET OPENXML
    OPTION OR ORDER OUTER OVER OVERLAPS PERCENT PIVOT PLACING PLAN PRECISION PRIMARY PRINT
    PROC PROCEDURE PUBLIC RAISERROR READ READTEXT RECONFIGURE REFERENCES REGEXP REPLICATION
    RESTORE RESTRICT RETURN RETURNING REVERT REVOKE RIGHT ROLLBACK ROWCOUNT ROWGUIDCOL RULE
    SAVE SCHEMA SECURITYAUDIT SELECT SESSION_USER SET SETUSER SHUTDOWN SIMILAR SOME
    STATISTICS SYMMETRIC SYSTEM_USER TABLE TABLESAMPLE TEXTSIZE THEN TO TOP TRAILING TRAN
    TRANSACTION TRIGGER TRUE TRUNCATE TRY_CONVERT TSEQUAL UNION UNIQUE UNPIVOT UPDATE
    UPDATETEXT USE USER USING VALUES VARIADIC VARYING VERBOSE VIEW WAITFOR WHEN WHERE WHILE
    WINDOW WITH WRITETEXT
    """.split()
)
