"""Validate a summary document against the structure this skill promises.

There is no Asciidoctor on this machine, so nothing renders the file and tells
you it is broken. The failures worth catching are not exotic syntax anyway —
they are the ones that come from writing AsciiDoc while thinking in Markdown
(``**fett**``, ``# Ueberschrift``, ``` ```code``` ```), and a missing piece of
the agreed structure.

Exit code 1 on errors, 0 otherwise; warnings never fail the run.

Usage:
    python check_adoc.py summary.adoc
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

# Attributes the agreed header carries; a missing one means the header was
# retyped instead of generated by adoc_header.py.
REQUIRED_ATTRIBUTES = (
    ':source-highlighter:', ':icons:', ':lang:', ':hyphens:', ':figure-caption!:',
)

# Delimiters that open and close a block with the identical line.
BLOCK_DELIMITERS = ('----', '====', '****', '____', '....', '|===', '////')

# Markdown constructs that stay silently unformatted in AsciiDoc.
MARKDOWN_TRAPS = (
    (re.compile(r'\*\*[^*\n]+\*\*'), 'Markdown-Fettschrift **text**, in AsciiDoc *text*'),
    (re.compile(r'^\s{0,3}#{1,6}\s'), 'Markdown-Ueberschrift #, in AsciiDoc = == ==='),
    (re.compile(r'^\s*```'), 'Markdown-Codefence ```, in AsciiDoc ---- oder [source]'),
    (re.compile(r'^\s*[-+]\s+\S'), 'Markdown-Aufzaehlung - oder +, in AsciiDoc *'),
    (re.compile(r'(?<!!)\[[^\]\n]+\]\((https?|\./|/)[^)\n]*\)'),
     'Markdown-Link [text](url), in AsciiDoc url[text]'),
)

ADMONITIONS = ('NOTE', 'TIP', 'IMPORTANT', 'WARNING', 'CAUTION')

# German numerals written out, including the "achtundsiebzig" compounds.
_TENS = 'zwanzig|dreissig|dreißig|vierzig|fuenfzig|fünfzig|sechzig|siebzig|achtzig|neunzig'
_ONES = 'zwei|drei|vier|fuenf|fünf|sechs|sieben|acht|neun'
# Order matters: the compound forms have to come before the bare ones, or the
# alternation matches "zwei" inside "zweihundert" and then finds no unit after it.
_SIMPLE = (f'(?:(?:{_ONES})?(?:hundert|tausend))|'
           'zehn|elf|zwoelf|zwölf|dreizehn|vierzehn|fuenfzehn|fünfzehn|'
           f'sechzehn|siebzehn|achtzehn|neunzehn|{_ONES}')

# Units that mark a figure the reader is meant to compare or look up. Deliberately
# without Jahre/Tage/Minuten: "sechzehn Jahre Fidesz-Regierung" is good prose,
# "achtundsiebzig Prozent" is a measurement hiding as one.
_UNITS = ('Prozent|Millionen?|Milliarden?|Billionen?|Dollar|Euro|Watt|Megawatt|'
          'Kilowatt|Grad|Meter|Kilometer|Sitze[n]?|Stimmen|Mandate[n]?|Uhr')

SPELLED_MEASURE = re.compile(
    rf'\b((?:(?:{_ONES})und)?(?:{_TENS})|{_SIMPLE})\s+({_UNITS})\b', re.IGNORECASE)


def in_verbatim(lines: list[str]) -> list[bool]:
    """Mark lines that sit inside a listing or literal block.

    Markdown-looking text is legitimate there — it is quoted, not formatted.
    """
    inside = False
    flags = []
    for line in lines:
        stripped = line.rstrip()
        if stripped in ('----', '....', '////'):
            inside = not inside
            flags.append(True)
            continue
        flags.append(inside)
    return flags


def check_header(lines: list[str], errors: list[str]) -> None:
    """The document must open with a title line and carry the agreed attributes."""
    if not lines or not lines[0].startswith('= '):
        errors.append('Zeile 1 ist kein Dokumenttitel ("= Titel").')
    head = '\n'.join(lines[:30])
    missing = [a for a in REQUIRED_ATTRIBUTES if a not in head]
    if missing:
        errors.append(f'Header-Attribute fehlen: {", ".join(missing)}. '
                      'Header mit adoc_header.py erzeugen.')


def check_structure(lines: list[str], errors: list[str], warnings: list[str]) -> None:
    """Check for the source data block, the abstract and sane heading levels."""
    body = '\n'.join(lines)
    if '[horizontal]' not in body or 'Quelle::' not in body:
        errors.append('Der Block mit den Videodaten fehlt (erwartet "[horizontal]" '
                      'mit "Quelle::").')
    leads = body.count('[.lead]')
    if leads != 1:
        errors.append(f'{leads} "[.lead]"-Absaetze gefunden, genau einer wird erwartet.')

    levels = [len(m.group(1)) for line in lines
              if (m := re.match(r'^(=+)\s+\S', line))]
    for previous, current in zip(levels, levels[1:]):
        if current > previous + 1:
            errors.append(f'Ueberschriftenebene springt von {"=" * previous} auf '
                          f'{"=" * current}.')
            break
    if len([lvl for lvl in levels if lvl == 2]) < 2:
        warnings.append('Weniger als zwei Abschnitte auf Ebene "==" — die '
                        'inhaltliche Gliederung fehlt vermutlich.')
    if not any(line.startswith(tuple(f'{a}:' for a in ADMONITIONS))
               or line.startswith(tuple(f'[{a}]' for a in ADMONITIONS))
               for line in lines):
        warnings.append('Keine Admonition gefunden — eigene Einordnung muss als '
                        'NOTE ausgewiesen werden.')


def check_blocks(lines: list[str], errors: list[str]) -> None:
    """Every block delimiter has to appear an even number of times."""
    counts: dict[str, int] = {}
    for line in lines:
        token = line.rstrip()
        if token in BLOCK_DELIMITERS:
            counts[token] = counts.get(token, 0) + 1
    for token, count in counts.items():
        if count % 2:
            errors.append(f'Blockbegrenzer {token!r} kommt {count}-mal vor — '
                          'ein Block ist nicht geschlossen.')


def check_markdown(lines: list[str], verbatim: list[bool], errors: list[str]) -> None:
    """Report Markdown syntax that AsciiDoc would print literally."""
    for number, (line, quoted) in enumerate(zip(lines, verbatim), start=1):
        if quoted or line.startswith('//'):
            continue
        for pattern, reason in MARKDOWN_TRAPS:
            if pattern.search(line):
                errors.append(f'Zeile {number}: {reason} — {line.strip()[:70]}')
                break


def check_spelled_numbers(lines: list[str], verbatim: list[bool],
                          warnings: list[str]) -> None:
    """Report measurements written as words instead of digits.

    German allows both spellings below a hundred, so the choice drifts within a
    document, and the mixture is what does the damage: "achtundsiebzig Prozent"
    two paragraphs from "779 Prozent" makes the figures incomparable.

    Two known nudges toward the wrong one, in case this fires a lot: the sibling
    skill `voiceover` prescribes spelled-out numerals for its own good reason (a
    speech synthesiser reads digits wrong) with the example "siebenundachtzig
    Tage", and a source video that speaks its figures aloud offers them the same
    way. Neither applies to a document that is read.
    """
    for number, (line, quoted) in enumerate(zip(lines, verbatim), start=1):
        if quoted:
            continue
        for match in SPELLED_MEASURE.finditer(line):
            warnings.append(f'Zeile {number}: "{match.group(0)}" als Zahlwort — '
                            'Messgroessen gehoeren als Ziffern ins Dokument.')


def check_attribute_refs(lines: list[str], verbatim: list[bool],
                         warnings: list[str]) -> None:
    """Curly braces are attribute references and swallow their content."""
    defined = {m.group(1) for line in lines
               if (m := re.match(r'^:([\w-]+)!?:', line))}
    known = defined | {'root_dir', 'github_url', 'counter', 'nbsp', 'sp', 'empty'}
    for number, (line, quoted) in enumerate(zip(lines, verbatim), start=1):
        if quoted:
            continue
        for ref in re.findall(r'\{([a-z][\w-]*)\}', line):
            if ref not in known:
                warnings.append(f'Zeile {number}: "{{{ref}}}" ist keine bekannte '
                                'Attributreferenz und wird beim Rendern leer.')


def main() -> None:
    """Run every check and report errors and warnings separately."""
    sys.stdout.reconfigure(encoding='utf-8', errors='replace')

    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument('adoc')
    args = ap.parse_args()

    lines = Path(args.adoc).read_text(encoding='utf-8').splitlines()
    verbatim = in_verbatim(lines)
    errors: list[str] = []
    warnings: list[str] = []

    check_header(lines, errors)
    check_structure(lines, errors, warnings)
    check_blocks(lines, errors)
    check_markdown(lines, verbatim, errors)
    check_spelled_numbers(lines, verbatim, warnings)
    check_attribute_refs(lines, verbatim, warnings)

    words = sum(len(line.split()) for line in lines)
    print(f'{args.adoc}: {len(lines)} Zeilen, rund {words} Woerter')
    for warning in warnings:
        print(f'  HINWEIS: {warning}')
    for error in errors:
        print(f'  FEHLER : {error}')
    if errors:
        sys.exit(1)
    print('OK')


if __name__ == '__main__':
    main()
